import { createContext, useContext, useState } from 'react';

const LangContext = createContext();

export const translations = {
  fr: {
    nav: {
      home: 'Accueil', about: 'À Propos', services: 'Services',
      projects: 'Projets', contact: 'Contact', cta: 'Nous contacter',
    },
    footer: {
      tagline: 'Des solutions digitales qui fonctionnent pour l\'Afrique. POS, ERP, SaaS — déployés en production.',
      nav: 'Navigation', contact: 'Contact', startProject: 'Démarrer un projet',
      builtIn: 'Conçu au', rights: 'Tous droits réservés.',
    },
    whatsapp: 'Bonjour KABRAK Eng, je souhaite discuter d\'un projet.',
    home: {
      heroTitle1: 'On code',
      heroTitle2: 'des logiciels',
      heroTitle3: 'qui tournent',
      heroTitle4: 'en production',
      heroSub: '5 SaaS déployés et utilisés au quotidien. POS, ERP, gestion optique, bureau de change, salons de beauté.',
      heroBtn1: 'Voir nos projets',
      heroBtn2: 'Nous contacter',
      trustPills: ['5 SaaS en production', 'Mobile-first', 'Mode hors-ligne', 'Déploiement sous 2 semaines'],
      servicesLabel: 'Ce qu\'on fait',
      servicesTitle: 'On construit, on déploie, on maintient',
      servicesSub: 'Pas de slides, du code.',
      servicesLink: 'Voir tous nos services',
      services: [
        { title: 'Logiciels SaaS', sub: 'Du code à la prod', desc: 'On a construit 5 plateformes SaaS en production. POS, ERP, gestion. On connaît le chemin.' },
        { title: 'Intelligence Artificielle', sub: 'Automatisation concrète', desc: 'Chatbots, prédictions de ventes, analyse de données. Intégré dans vos outils existants.' },
        { title: 'Mode hors-ligne', sub: 'Pour l\'Afrique', desc: 'Vos applications marchent sans internet. Sync cloud au retour. Mobile Money intégré.' },
      ],
      impactLabel: 'En chiffres',
      impactTitle1: 'Ce qu\'on a',
      impactTitle2: 'livré',
      impactSub: 'Pas de promesses, des produits en production.',
      stats: [
        { num: '5', label: 'SaaS en production' },
        { num: '15+', label: 'Projets livrés' },
        { num: '2 sem.', label: 'Délai MVP moyen' },
        { num: '100%', label: 'Code maintenable' },
      ],
      pillars: [
        { title: 'On code, on déploie', desc: 'MVP en 2 semaines. Pas de réunions infinies.' },
        { title: 'Marche hors-ligne', desc: 'Vos apps fonctionnent sans internet. Sync au retour.' },
        { title: 'Contexte local', desc: 'Mobile Money, 3G, français/anglais. On vit ici.' },
      ],
      featuredLabel: 'Projet phare',
      featuredTitle: 'Ce qu\'on a construit',
      featuredBadge: 'En production',
      featuredDesc: 'Plateforme SaaS pour opticiens : ventes, inventaire, patients, assurances. Multi-tenant, multi-magasins, PDF automatisés.',
      featuredVisit: 'Visiter kabrakopticpro.com',
      featuredMore: 'En savoir plus',
      featuredAllProjects: 'Voir tous les projets',
      testimonialsLabel: 'Témoignages',
      testimonialsTitle: 'Ce qu\'ils disent de nous',
      testimonials: [
        { name: 'Nabil A.', role: 'Saoudia Optique — Douala', quote: 'Livraison en 2 semaines. Interface claire, performance au top.' },
        { name: 'Thierry Bogo', role: 'Bogo System — Douala', quote: 'Le logiciel a transformé nos opérations. Rapide et fiable.' },
        { name: 'Aminatou K.', role: 'Cabinet Optique — Yaoundé', quote: 'Équipe professionnelle. Plateforme simple et efficace.' },
      ],
      ctaTitle: 'Un projet en tête ?',
      ctaSub: '30 minutes de call, on vous dit si c\'est faisable et à quel prix.',
      ctaBtn1: 'Démarrer',
      ctaBtn2: 'Nos projets',
    },
    about: {
      label: 'Notre histoire',
      title: 'À propos de',
      sub: 'Studio tech basé au Cameroun. On construit des logiciels qu\'on utilise nous-mêmes.',
      whoLabel: 'Qui on est',
      whoTitle1: 'Des développeurs',
      whoTitle2: 'qui livrent',
      whoP1: 'KABRAK Eng, c\'est une équipe de développeurs au Cameroun qui construit des plateformes SaaS depuis 2024. 5 produits en production, utilisés par des commerçants, opticiens et salons de beauté.',
      whoP2: 'On ne fait pas que vendre du code — on construit des produits qu\'on maintient, qu\'on améliore, et qui tournent tous les jours chez nos clients.',
      tags: ['Cameroun', 'Tech africaine', '5 SaaS en prod', 'Depuis 2024'],
      guideTitle: 'Ce qui nous guide',
      mission: { title: 'Notre Mission', desc: 'Construire des logiciels qui marchent en Afrique — pas des démos.' },
      vision: { title: 'Notre Vision', desc: 'Couvrir tous les secteurs: commerce, santé, beauté, finance.' },
      values: { title: 'Nos Valeurs', desc: 'On code, on déploie, on maintient. Pas de promesses, des livraisons.' },
      whyLabel: 'Pourquoi nous',
      whyTitle: 'Ce qui nous différencie',
      why: [
        { title: 'On livre en 2 semaines', desc: 'MVP fonctionnel, pas de PowerPoint.' },
        { title: 'On vit ici', desc: '3G, Mobile Money, coupures courant. On connaît.' },
        { title: 'Code maintenable', desc: 'Architecture propre, documentée, scalable.' },
        { title: 'Contact direct', desc: 'Vous parlez aux développeurs, pas à un commercial.' },
      ],
      ctaTitle: 'Travaillons ensemble',
      ctaSub: 'Un projet ou une idée ? On vous dit si c\'est faisable.',
      ctaBtn: 'Démarrer',
    },
    services: {
      label: 'Ce qu\'on fait',
      title: 'Nos',
      titleSpan: 'Services',
      sub: 'Du site vitrine au SaaS multi-tenant. On a déjà construit les 5.',
      quoteBtn: 'Demander un devis',
      processLabel: 'Comment ça marche',
      processTitle: 'Notre processus',
      process: [
        { num: '01', title: 'Call 30 min', desc: 'On comprend votre besoin. On dit si c\'est faisable.' },
        { num: '02', title: 'Devis sous 48h', desc: 'Prix fixe, planning précis. Pas d\'estimations floues.' },
        { num: '03', title: 'On code', desc: 'Sprints de 2 semaines. Démo à chaque étape.' },
        { num: '04', title: 'En production', desc: 'Déploiement, formation, support. Ça tourne.' },
      ],
      ctaBadge: 'Réponse sous 24h',
      ctaTitle: 'Un projet ?',
      ctaSub: 'Décrivez votre idée. On vous dit si c\'est faisable et à quel prix.',
      ctaBtn: 'Devis gratuit',
      list: [
        { title: 'Logiciels SaaS', subtitle: 'On en a construit 5', desc: 'Plateformes multi-tenant, dashboards, API. On connaît le chemin du MVP à la prod.', features: ['Application web / SaaS', 'Dashboard', 'API & intégrations', 'Multi-tenant', 'Maintenance'] },
        { title: 'Intelligence Artificielle', subtitle: 'Automatisation concrète', desc: 'Chatbots, prédictions de ventes, analyse de données. Intégré dans vos outils.', features: ['Chatbot IA', 'Prédictions', 'Analyse de données', 'Automatisation', 'NLP'], badge: 'Populaire' },
        { title: 'Applications Mobiles', subtitle: 'Android & iOS', desc: 'Apps cross-platform. Hors-ligne, Mobile Money, push notifications.', features: ['App Android & iOS', 'Interface simple', 'Mode hors-ligne', 'Mobile Money', 'Push notifications'] },
        { title: 'ERP & CRM', subtitle: 'Gestion d\'entreprise', desc: 'On a construit un ERP supermarché complet. Le vôtre est faisable.', features: ['ERP sur-mesure', 'CRM', 'Gestion stock', 'Comptabilité', 'Formation incluse'] },
        { title: 'Data & Analytics', subtitle: 'Vos données en clair', desc: 'Dashboards temps réel, rapports automatisés. Prenez de meilleures décisions.', features: ['Dashboard temps réel', 'Rapports auto', 'KPIs métier', 'Analyse tendances', 'Exports'] },
        { title: 'Déploiement & Infra', subtitle: 'Ça tourne, ça reste up', desc: 'Cloud, SSL, sauvegardes auto, monitoring. On gère la prod pour vous.', features: ['Déploiement cloud', 'SSL, HTTPS', 'Sauvegardes auto', 'Monitoring', 'Support 24/7'] },
      ],
    },
    projects: {
      label: 'Réalisations',
      title: 'Nos',
      titleSpan: 'Projets',
      sub: '5 SaaS en production. Pas des démos — des produits qui tournent.',
      opticBadge: 'En production · kabrakopticpro.com',
      opticVisitBtn: 'Visiter kabrakopticpro.com',
      opticSimilarBtn: 'Projet similaire ?',
      opticDesc: 'Une plateforme SaaS complète pour les opticiens — gestion des ventes, inventaire, patients, assurances et prescriptions en un seul endroit. Multi-tenant, multi-magasins, PDF automatisés, analytics temps réel.',
      opticFeatures: ['Gestion multi-magasins', 'Prescriptions & ordonnances PDF', 'Suivi patients & historique', 'Gestion des stocks', 'Assurances & mutuelles', 'Analytics temps réel'],
      opticSubtitle: 'Plateforme SaaS · Gestion optique',
      opticStats: [
        { num: 'Multi-magasins', label: 'Architecture scalable' },
        { num: 'PDF auto', label: 'Factures & bordereaux' },
        { num: 'Temps réel', label: 'Analytics & notifications' },
      ],
      featuredBadge: 'Projet phare · En production',
      exchangeBadge: 'En production · exchange.kabrakeng.com',
      exchangeVisitBtn: 'Visiter exchange.kabrakeng.com',
      exchangeSimilarBtn: 'Projet similaire ?',
      exchangeTitle: 'KABRAK Exchange',
      exchangeSubtitle: 'Logiciel de gestion · Bureau de change',
      exchangeDesc: 'Un logiciel sur-mesure pour les bureaux de change — gestion des opérations de change, suivi des transactions, rapports financiers et caisse en temps réel. Conçu pour les réalités du marché camerounais.',
      exchangeFeatures: ['Gestion des devises', 'Suivi transactions en temps réel', 'Caisse & balance quotidienne', 'Rapports financiers PDF', 'Historique complet des opérations', 'Interface simple et rapide'],
      exchangeStats: [
        { num: 'Temps réel', label: 'Suivi des transactions' },
        { num: 'PDF auto', label: 'Rapports financiers' },
        { num: 'Multi-devises', label: 'Gestion complète' },
      ],
      beautyBadge: 'En production · beautyspa.kabrakeng.com',
      beautyVisitBtn: 'Visiter beautyspa.kabrakeng.com',
      beautySimilarBtn: 'Projet similaire ?',
      beautyTitle: 'KABRAK Beauty & Spa Pro',
      beautySubtitle: 'Plateforme SaaS · Gestion salon de beauté',
      beautyDesc: 'Une application SaaS complète pour les salons de beauté, barbershops et instituts de soin — gestion des rendez-vous, clients, équipe, caisse rapide, facturation et abonnements. Thème adaptatif beauté ou barbershop.',
      beautyFeatures: ['Gestion des rendez-vous', 'Caisse rapide & facturation', 'Gestion équipe & commissions', 'Abonnements & plans tarifaires', 'Thème beauté ou barbershop', 'PWA mobile iOS & Android'],
      beautyStats: [
        { num: 'PWA', label: 'iOS & Android' },
        { num: 'Multi-thèmes', label: 'Beauté & Barbershop' },
        { num: 'Temps réel', label: 'Caisse & rendez-vous' },
      ],
      retailBadge: 'En production · Supermarché',
      retailVisitBtn: 'Voir la proposition',
      retailSimilarBtn: 'Projet similaire ?',
      retailTitle: 'KABRAK Retail ERP',
      retailSubtitle: 'ERP Hybride · Gestion Supermarché',
      retailDesc: 'Un ERP complet pour supermarchés et commerces de détail — point de vente (POS), gestion de stock en temps réel, facturation, achats & fournisseurs, comptabilité, rapports et gestion d\'équipe. Mode hybride: installation locale (hors-ligne) + synchronisation cloud.',
      retailFeatures: ['Point de vente (POS) rapide', 'Stock en temps réel + alertes', 'Facturation avec QR code', 'Achats & bons de commande', 'Comptabilité & compte de résultat', 'Mode hors-ligne + sync cloud'],
      retailStats: [
        { num: 'Hybride', label: 'Local + Cloud' },
        { num: '12 modules', label: 'ERP complet' },
        { num: 'Hors-ligne', label: 'Fonctionne sans internet' },
      ],
      ctaTitle: 'Un projet similaire ?',
      ctaSub: '30 min de call. On vous dit si c\'est faisable et à quel prix.',
      ctaBtn1: 'Discuter d\'un projet',
      ctaBtn2: 'Voir nos réalisations',
    },
    contact: {
      label: 'Parlons-en',
      title: 'Contactez-nous',
      sub: 'Un projet, une idée, un besoin ? WhatsApp ou email — on répond vite.',
      waTitle: 'WhatsApp Direct',
      waSub: 'Le plus rapide. Réponse en moins d\'1h en journée.',
      waBtn: 'Écrire sur WhatsApp',
      availability: 'Lun–Sam, 8h–18h WAT',
      location: 'Cameroun — Afrique centrale',
      formTitle: 'Envoyez un message',
      formSub: 'Décrivez votre projet. On vous dit si c\'est faisable et à quel prix.',
      labelName: 'Nom complet *',
      labelEmail: 'Email *',
      labelService: 'Type de projet',
      labelMsg: 'Votre message *',
      placeholderName: 'Moussa Njike',
      placeholderEmail: 'vous@exemple.com',
      placeholderMsg: 'Qu\'est-ce que vous voulez construire ? Budget estimé, délai souhaité...',
      serviceOptions: ['Développement Web', 'Application Mobile', 'Intelligence Artificielle', 'Solutions Digitales', 'Data & Analytics', 'Sécurité & Infrastructure', 'Autre'],
      sendBtn: 'Envoyer le message',
      sending: 'Envoi en cours...',
      sentTitle: 'Message envoyé !',
      sentSub: 'Merci pour votre message. On vous répond dans les 24h. En attendant, vous pouvez aussi nous joindre sur WhatsApp.',
      continueWa: 'Continuer sur WhatsApp',
      nextTitle: 'Ce qui se passe ensuite',
      nextSteps: ['On vous répond sous 24h', 'Appel découverte de 30 min', 'Devis détaillé sous 48h', 'Démarrage du projet'],
    },
  },
  en: {
    nav: {
      home: 'Home', about: 'About', services: 'Services',
      projects: 'Projects', contact: 'Contact', cta: 'Contact us',
    },
    footer: {
      tagline: 'Digital solutions that work for Africa. POS, ERP, SaaS — deployed in production.',
      nav: 'Navigation', contact: 'Contact', startProject: 'Start a project',
      builtIn: 'Built in', rights: 'All rights reserved.',
    },
    whatsapp: 'Hello KABRAK Eng, I would like to discuss a project.',
    home: {
      heroTitle1: 'We build',
      heroTitle2: 'software',
      heroTitle3: 'that runs',
      heroTitle4: 'in production',
      heroSub: '5 SaaS deployed and used daily. POS, ERP, optical management, currency exchange, beauty salons.',
      heroBtn1: 'See our projects',
      heroBtn2: 'Contact us',
      trustPills: ['5 SaaS in production', 'Mobile-first', 'Offline mode', 'Deploy in 2 weeks'],
      servicesLabel: 'What we do',
      servicesTitle: 'We build, deploy, maintain',
      servicesSub: 'No slides, just code.',
      servicesLink: 'View all services',
      services: [
        { title: 'SaaS Software', sub: 'From code to prod', desc: 'We built 5 SaaS platforms in production. POS, ERP, management. We know the path.' },
        { title: 'Artificial Intelligence', sub: 'Practical automation', desc: 'Chatbots, sales predictions, data analysis. Integrated into your existing tools.' },
        { title: 'Offline-first', sub: 'Built for Africa', desc: 'Your apps work without internet. Cloud sync when back online. Mobile Money integrated.' },
      ],
      impactLabel: 'By the numbers',
      impactTitle1: 'What we\'ve',
      impactTitle2: 'shipped',
      impactSub: 'No promises, products in production.',
      stats: [
        { num: '5', label: 'SaaS in production' },
        { num: '15+', label: 'Projects delivered' },
        { num: '2 wks', label: 'Average MVP time' },
        { num: '100%', label: 'Maintainable code' },
      ],
      pillars: [
        { title: 'We code, we ship', desc: 'MVP in 2 weeks. No endless meetings.' },
        { title: 'Works offline', desc: 'Your apps run without internet. Sync when back.' },
        { title: 'Local context', desc: 'Mobile Money, 3G, French/English. We live here.' },
      ],
      featuredLabel: 'Featured project',
      featuredTitle: 'What we\'ve built',
      featuredBadge: 'Live in production',
      featuredDesc: 'A complete SaaS platform for opticians — sales management, inventory, patients, insurance and prescriptions in one place. Multi-tenant, multi-store, automated PDFs, real-time analytics.',
      featuredVisit: 'Visit kabrakopticpro.com',
      featuredMore: 'Learn more',
      featuredAllProjects: 'View all projects',
      testimonialsLabel: 'Testimonials',
      testimonialsTitle: 'What our clients say',
      testimonials: [
        { name: 'Nabil A.', role: 'Manager, Saoudia Optique — Douala', quote: 'KABRAK Eng delivered in 2 weeks what I had been waiting for for months. Clean interface, top performance — exactly what I needed.' },
        { name: 'Thierry Bogo', role: 'Director, Bogo System — Exchange office', quote: 'The management software they developed for our exchange office transformed our operations. Fast, reliable and perfectly tailored to our needs.' },
        { name: 'Aminatou K.', role: 'Manager, Optique Cabinet — Yaoundé', quote: 'Very professional and responsive team. The platform simplifies our daily management and our clients are impressed by the smoothness of the service.' },
      ],
      ctaTitle: 'Got a project?',
      ctaSub: '30-min call, we tell you if it\'s doable and at what price.',
      ctaBtn1: 'Start a project',
      ctaBtn2: 'View our projects',
    },
    about: {
      label: 'Our story',
      title: 'About',
      sub: 'Tech studio based in Cameroon. We build software we use ourselves.',
      whoLabel: 'Who we are',
      whoTitle1: 'Developers',
      whoTitle2: 'who ship',
      whoP1: 'KABRAK Eng is a team of developers in Cameroon building SaaS platforms since 2024. 5 products in production, used by shop owners, opticians and beauty salons.',
      whoP2: 'We don\'t just sell code — we build products we maintain, improve, and that run every day for our clients.',
      tags: ['Cameroon', 'African tech', '5 SaaS live', 'Since 2024'],
      guideTitle: 'What drives us',
      mission: { title: 'Our Mission', desc: 'Build software that works in Africa — not demos.' },
      vision: { title: 'Our Vision', desc: 'Cover every sector: retail, health, beauty, finance.' },
      values: { title: 'Our Values', desc: 'We code, we deploy, we maintain. No promises, deliveries.' },
      whyLabel: 'Why us',
      whyTitle: 'What sets us apart',
      why: [
        { title: 'We ship in 2 weeks', desc: 'Working MVP, no PowerPoint.' },
        { title: 'We live here', desc: '3G, Mobile Money, power cuts. We know.' },
        { title: 'Maintainable code', desc: 'Clean, documented, scalable architecture.' },
        { title: 'Direct contact', desc: 'You talk to developers, not sales.' },
      ],
      ctaTitle: 'Let\'s work together',
      ctaSub: 'A project or an idea? We tell you if it\'s doable.',
      ctaBtn: 'Start the conversation',
    },
    services: {
      label: 'What we do',
      title: 'Our',
      titleSpan: 'Services',
      sub: 'From a landing page to a multi-tenant SaaS. We\'ve built 5 already.',
      quoteBtn: 'Request a quote',
      processLabel: 'How it works',
      processTitle: 'Our process',
      process: [
        { num: '01', title: '30-min call', desc: 'We understand your need. We tell you if it\'s doable.' },
        { num: '02', title: 'Quote in 48h', desc: 'Fixed price, precise timeline. No vague estimates.' },
        { num: '03', title: 'We code', desc: '2-week sprints. Demo at every step.' },
        { num: '04', title: 'In production', desc: 'Deploy, train, support. It runs.' },
      ],
      ctaBadge: 'Response within 24h',
      ctaTitle: 'Got a project?',
      ctaSub: 'Describe your idea. We tell you if it\'s doable and at what price.',
      ctaBtn: 'Get a free quote',
      list: [
        { title: 'SaaS Software', subtitle: 'We\'ve built 5', desc: 'Multi-tenant platforms, dashboards, APIs. We know the path from MVP to prod.', features: ['Web app / SaaS', 'Dashboard', 'API & integrations', 'Multi-tenant', 'Maintenance'] },
        { title: 'Artificial Intelligence', subtitle: 'Practical automation', desc: 'Chatbots, sales predictions, data analysis. Integrated into your tools.', features: ['Chatbot & AI assistant', 'Predictions & recommendations', 'Data analysis', 'Task automation', 'Natural language processing'], badge: 'Popular' },
        { title: 'Mobile Applications', subtitle: 'Android & iOS', desc: 'Cross-platform apps. Offline, Mobile Money, push notifications.', features: ['Android & iOS app', 'Intuitive interface', 'Offline mode', 'Mobile Money', 'Push notifications'] },
        { title: 'ERP & CRM', subtitle: 'Business management', desc: 'We built a complete supermarket ERP. Yours is doable.', features: ['Custom ERP', 'CRM', 'Inventory management', 'Accounting', 'Training included'] },
        { title: 'Data & Analytics', subtitle: 'Your data, clear', desc: 'Real-time dashboards, automated reports. Make better decisions.', features: ['Real-time dashboards', 'Auto reports', 'Business KPIs', 'Trend analysis', 'Exports'] },
        { title: 'Deploy & Infra', subtitle: 'It runs, it stays up', desc: 'Cloud, SSL, auto backups, monitoring. We handle prod for you.', features: ['Cloud deployment', 'SSL, HTTPS', 'Auto backups', 'Monitoring', '24/7 support'] },
      ],
    },
    projects: {
      label: 'Portfolio',
      title: 'Our',
      titleSpan: 'Projects',
      sub: '5 SaaS in production. Not demos — products that run.',
      opticBadge: 'Live · kabrakopticpro.com',
      opticVisitBtn: 'Visit kabrakopticpro.com',
      opticSimilarBtn: 'Similar project?',
      opticDesc: 'A complete SaaS platform for opticians — sales management, inventory, patients, insurance and prescriptions in one place. Multi-tenant, multi-store, automated PDFs, real-time analytics.',
      opticFeatures: ['Multi-store management', 'PDF prescriptions & orders', 'Patient tracking & history', 'Inventory management', 'Insurance & mutual funds', 'Real-time analytics'],
      opticSubtitle: 'SaaS Platform · Optical Management',
      opticStats: [
        { num: 'Multi-store', label: 'Scalable architecture' },
        { num: 'Auto PDF', label: 'Invoices & reports' },
        { num: 'Real-time', label: 'Analytics & notifications' },
      ],
      featuredBadge: 'Featured project · Live',
      exchangeBadge: 'Live · exchange.kabrakeng.com',
      exchangeVisitBtn: 'Visit exchange.kabrakeng.com',
      exchangeSimilarBtn: 'Similar project?',
      exchangeTitle: 'KABRAK Exchange',
      exchangeSubtitle: 'Management Software · Bureau de Change',
      exchangeDesc: 'Custom software for currency exchange offices — exchange operations management, transaction tracking, financial reports and real-time cash register. Built for the Cameroonian market realities.',
      exchangeFeatures: ['Currency management', 'Real-time transaction tracking', 'Daily cash & balance', 'PDF financial reports', 'Full operations history', 'Simple and fast interface'],
      exchangeStats: [
        { num: 'Real-time', label: 'Transaction tracking' },
        { num: 'Auto PDF', label: 'Financial reports' },
        { num: 'Multi-currency', label: 'Full management' },
      ],
      beautyBadge: 'Live · beautyspa.kabrakeng.com',
      beautyVisitBtn: 'Visit beautyspa.kabrakeng.com',
      beautySimilarBtn: 'Similar project?',
      beautyTitle: 'KABRAK Beauty & Spa Pro',
      beautySubtitle: 'SaaS Platform · Beauty Salon Management',
      beautyDesc: 'A complete SaaS app for beauty salons, barbershops and spas — appointment management, clients, team, quick checkout, invoicing and subscriptions. Adaptive theme for beauty or barbershop.',
      beautyFeatures: ['Appointment management', 'Quick checkout & invoicing', 'Team & commission management', 'Subscriptions & pricing plans', 'Beauty or barbershop theme', 'Mobile PWA iOS & Android'],
      beautyStats: [
        { num: 'PWA', label: 'iOS & Android' },
        { num: 'Multi-theme', label: 'Beauty & Barbershop' },
        { num: 'Real-time', label: 'Checkout & appointments' },
      ],
      retailBadge: 'Live · Supermarket',
      retailVisitBtn: 'View proposal',
      retailSimilarBtn: 'Similar project?',
      retailTitle: 'KABRAK Retail ERP',
      retailSubtitle: 'Hybrid ERP · Supermarket Management',
      retailDesc: 'A complete ERP for supermarkets and retail businesses — point of sale (POS), real-time inventory management, invoicing, purchases & suppliers, accounting, reports and team management. Hybrid mode: local installation (offline) + cloud synchronization.',
      retailFeatures: ['Fast point of sale (POS)', 'Real-time stock + alerts', 'Invoicing with QR code', 'Purchases & purchase orders', 'Accounting & profit & loss', 'Offline mode + cloud sync'],
      retailStats: [
        { num: 'Hybrid', label: 'Local + Cloud' },
        { num: '12 modules', label: 'Complete ERP' },
        { num: 'Offline', label: 'Works without internet' },
      ],
      ctaTitle: 'A similar project?',
      ctaSub: '30-min call. We tell you if it\'s doable and at what price.',
      ctaBtn1: 'Discuss a project',
      ctaBtn2: 'See our work',
    },
    contact: {
      label: 'Let\'s talk',
      title: 'Contact us',
      sub: 'A project, an idea, a need? WhatsApp or email — we reply fast.',
      waTitle: 'WhatsApp Direct',
      waSub: 'Fastest way. Response within 1h during business hours.',
      waBtn: 'Write on WhatsApp',
      availability: 'Mon–Sat, 8am–6pm WAT',
      location: 'Cameroon — Central Africa',
      formTitle: 'Send a message',
      formSub: 'Describe your project. We tell you if it\'s doable and at what price.',
      labelName: 'Full name *',
      labelEmail: 'Email *',
      labelService: 'Project type',
      labelMsg: 'Your message *',
      placeholderName: 'Moussa Njike',
      placeholderEmail: 'you@example.com',
      placeholderMsg: 'What do you want to build? Estimated budget, desired timeline...',
      serviceOptions: ['Web Development', 'Mobile Application', 'Artificial Intelligence', 'Digital Solutions', 'Data & Analytics', 'Security & Infrastructure', 'Other'],
      sendBtn: 'Send message',
      sending: 'Sending...',
      sentTitle: 'Message sent!',
      sentSub: 'Thank you for your message. We\'ll reply within 24h. In the meantime, you can also reach us on WhatsApp.',
      continueWa: 'Continue on WhatsApp',
      nextTitle: 'What happens next',
      nextSteps: ['We reply within 24h', '30-min discovery call', 'Detailed quote within 48h', 'Project kickoff'],
    },
  },
};

export function LangProvider({ children }) {
  const [lang, setLang] = useState('fr');
  const t = translations[lang];
  return (
    <LangContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LangContext.Provider>
  );
}

export function useLang() {
  return useContext(LangContext);
}
