import { createContext, useContext, useState } from 'react';

const LangContext = createContext();

export const translations = {
  fr: {
    nav: {
      home: 'Accueil', about: 'À Propos', services: 'Services',
      projects: 'Projets', contact: 'Contact', cta: 'Nous contacter',
    },
    footer: {
      tagline: 'Des solutions digitales qui fonctionnent pour l\'Afrique. Conçu et développé au Cameroun.',
      nav: 'Navigation', contact: 'Contact', startProject: 'Démarrer un projet',
      builtIn: 'Conçu au', rights: 'Tous droits réservés.',
    },
    whatsapp: 'Bonjour KABRAK Eng, je souhaite discuter d\'un projet.',
    home: {
      heroTitle1: 'Empowering African',
      heroTitle2: 'Businesses',
      heroTitle3: 'Through',
      heroTitle4: 'Smart Technology',
      heroSub: 'KABRAK Eng conçoit des solutions digitales sur-mesure adaptées aux réalités africaines — rapides, robustes et pensées pour scaler.',
      heroBtn1: 'Découvrir nos services',
      heroBtn2: 'Nous contacter',
      trustPills: ['100% Made in Africa', 'Mobile-first', 'Low-bandwidth ready', 'Livraison rapide'],
      servicesLabel: 'Ce que nous faisons',
      servicesTitle: 'Nos domaines d\'expertise',
      servicesSub: 'Des solutions concrètes qui simplifient, automatisent et transforment votre business.',
      servicesLink: 'Voir tous nos services',
      services: [
        { title: 'Développement Logiciel', sub: 'Plateformes, SaaS & applications web', desc: 'Applications web sur-mesure et plateformes SaaS complètes. Du prototype au produit scalable, nous gérons tout le cycle.' },
        { title: 'Intelligence Artificielle', sub: 'Automatisation & prédictions', desc: 'Automatisez vos processus, prenez de meilleures décisions. Chatbots, prédictions de ventes, recommandations intelligentes.' },
        { title: 'Solutions Digitales', sub: 'Outils pensés pour l\'Afrique', desc: 'Des outils adaptés aux contraintes locales : connexion lente, Mobile Money, interfaces simples et puissantes.' },
      ],
      impactLabel: 'Notre impact',
      impactTitle1: 'We build technology',
      impactTitle2: 'that works for Africa',
      impactSub: 'Nous créons des solutions adaptées aux réalités africaines — accessibles, durables et prêtes à scaler.',
      stats: [
        { num: '+10', label: 'Projets réalisés' },
        { num: '+5', label: 'Clients satisfaits' },
        { num: '1', label: 'Produit SaaS live' },
        { num: '100%', label: 'Focus Afrique' },
      ],
      pillars: [
        { title: 'Digitalisation des PME', desc: 'Aider les petites et moyennes entreprises à passer au numérique efficacement.' },
        { title: 'Productivité accrue', desc: 'Nos outils réduisent le travail manuel et augmentent les revenus de nos clients.' },
        { title: 'Tech accessible', desc: 'Interfaces optimisées pour la 3G, Mobile Money intégré, mode hors-ligne.' },
      ],
      featuredLabel: 'Projet phare',
      featuredTitle: 'Ce que nous avons construit',
      featuredBadge: 'Déjà utilisé en conditions réelles',
      featuredDesc: 'Une plateforme SaaS complète pour les opticiens — gestion des ventes, inventaire, patients, assurances et prescriptions en un seul endroit. Multi-tenant, multi-magasins, PDF automatisés, analytics temps réel.',
      featuredVisit: 'Visiter kabrakopticpro.com',
      featuredMore: 'En savoir plus',
      featuredAllProjects: 'Voir tous les projets',
      testimonialsLabel: 'Témoignages',
      testimonialsTitle: 'Ce qu\'ils disent de nous',
      testimonials: [
        { name: 'Nabil A.', role: 'Gérant, Saoudia Optique — Douala', quote: 'KABRAK Eng a livré en 2 semaines ce que j\'attendais depuis des mois. Interface claire, performance au top — exactement ce dont j\'avais besoin.' },
        { name: 'Thierry Bogo', role: 'Directeur, Bogo System — Bureau de change', quote: 'Le logiciel de gestion qu\'ils ont développé pour notre bureau de change a transformé nos opérations. Rapide, fiable et parfaitement adapté à nos besoins.' },
        { name: 'Aminatou K.', role: 'Responsable, Cabinet Optique — Yaoundé', quote: 'Équipe très professionnelle et réactive. La plateforme simplifie notre gestion quotidienne et nos clients sont impressionnés par la fluidité du service.' },
      ],
      ctaTitle: 'Prêt à transformer votre business ?',
      ctaSub: 'Discutons de votre projet. En 30 minutes, on vous propose une solution concrète et adaptée à votre budget.',
      ctaBtn1: 'Démarrer un projet',
      ctaBtn2: 'Voir nos projets',
    },
    about: {
      label: 'Notre histoire',
      title: 'À propos de',
      sub: 'Une entreprise technologique née en Afrique, construite pour l\'Afrique — avec une ambition mondiale.',
      whoLabel: 'Qui sommes-nous',
      whoTitle1: 'La tech au service des',
      whoTitle2: 'entrepreneurs africains',
      whoP1: 'KABRAK Eng est une entreprise spécialisée dans la création de solutions technologiques adaptées aux défis africains. Nous concevons des plateformes logicielles, des applications web et des outils numériques qui fonctionnent vraiment dans les conditions locales — connexion limitée, Mobile Money, interfaces en français.',
      whoP2: 'Notre ambition : devenir le partenaire tech de référence pour les PME et startups d\'Afrique centrale et subsaharienne, en construisant des solutions qui peuvent scaler et compétir à l\'échelle internationale.',
      tags: ['Cameroun 🇨🇲', 'Tech africaine', 'Startup mindset', 'International'],
      guideTitle: 'Ce qui nous guide',
      mission: { title: 'Notre Mission', desc: 'Créer des outils numériques accessibles qui aident les entreprises africaines à être plus efficaces, plus compétitives et plus rentables.' },
      vision: { title: 'Notre Vision', desc: 'Être reconnus comme le studio tech africain de référence, capable de construire des produits de classe mondiale depuis le continent.' },
      values: { title: 'Nos Valeurs', desc: 'Excellence sans compromis, proximité client, innovation adaptée. Nous livrons ce que nous promettons, dans les délais.' },
      whyLabel: 'Pourquoi nous choisir',
      whyTitle: 'Ce qui nous différencie',
      why: [
        { title: 'Livraison rapide', desc: 'MVP en 2 semaines. Pas de promesses vides — on code.' },
        { title: 'Context africain', desc: '3G, Mobile Money, langues locales. On comprend votre marché.' },
        { title: 'Code de qualité', desc: 'Architecture propre, scalable et maintainable sur le long terme.' },
        { title: 'Proximité client', desc: 'Un interlocuteur dédié. Vous parlez directement aux développeurs.' },
      ],
      ctaTitle: 'Travaillons ensemble',
      ctaSub: 'Vous avez un projet, une idée ou un problème à résoudre ? On est là pour ça.',
      ctaBtn: 'Démarrer la conversation',
    },
    services: {
      label: 'Ce que nous faisons',
      title: 'Nos',
      titleSpan: 'Services',
      sub: 'Du site vitrine à la plateforme SaaS complexe — nous couvrons tout le spectre du développement digital, adapté aux besoins et réalités africaines.',
      quoteBtn: 'Demander un devis',
      processLabel: 'Comment ça marche',
      processTitle: 'Notre processus',
      process: [
        { num: '01', title: 'Découverte', desc: 'Appel de 30 min pour comprendre vos besoins, budget et délais.' },
        { num: '02', title: 'Proposition', desc: 'Devis détaillé, planning et architecture technique sous 48h.' },
        { num: '03', title: 'Développement', desc: 'Sprints courts avec démos régulières. Vous suivez l\'avancement.' },
        { num: '04', title: 'Livraison', desc: 'Déploiement, formation et support inclus dans chaque projet.' },
      ],
      ctaBadge: 'Réponse sous 24h garantie',
      ctaTitle: 'Vous avez un projet en tête ?',
      ctaSub: 'Décrivez-nous votre idée. On vous propose une solution concrète, un délai et un budget réaliste.',
      ctaBtn: 'Obtenir un devis gratuit',
      list: [
        { title: 'Développement Web', subtitle: 'Sites & plateformes sur-mesure', desc: 'Applications web modernes, plateformes SaaS, dashboards, portails clients. Code propre et livraison rapide.', features: ['Site vitrine professionnel', 'Application web / SaaS', 'Dashboard & back-office', 'API REST & intégrations', 'Déploiement & maintenance'] },
        { title: 'Intelligence Artificielle', subtitle: 'Automatisation & prédictions', desc: 'Intégrez l\'IA dans vos processus métier. Chatbots intelligents, analyse de données, prédictions de ventes.', features: ['Chatbot & assistant IA', 'Prédictions & recommandations', 'Analyse de données', 'Automatisation des tâches', 'Traitement du langage naturel'], badge: 'Populaire' },
        { title: 'Applications Mobiles', subtitle: 'Android & iOS', desc: 'Applications mobiles cross-platform performantes. Interface intuitive, mode hors-ligne, Mobile Money intégré.', features: ['App Android & iOS', 'Interface intuitive mobile-first', 'Mode hors-ligne', 'Intégration Mobile Money', 'Notifications push'] },
        { title: 'Solutions Digitales', subtitle: 'Transformation numérique', desc: 'Digitalisez vos processus internes, automatisez vos workflows et gagnez en efficacité opérationnelle.', features: ['Audit digital & conseil', 'Digitalisation des processus', 'Systèmes de gestion (ERP/CRM)', 'Formation & accompagnement', 'Support & maintenance'] },
        { title: 'Data & Analytics', subtitle: 'Vos données, vos décisions', desc: 'Transformez vos données brutes en insights actionnables. Tableaux de bord en temps réel, rapports automatisés.', features: ['Tableaux de bord temps réel', 'Rapports automatisés', 'KPIs & métriques métier', 'Analyse de tendances', 'Exports & intégrations'] },
        { title: 'Sécurité & Infrastructure', subtitle: 'Fiable, sécurisé, scalable', desc: 'Audit de sécurité, mise en place de serveurs, déploiement cloud, sauvegardes automatiques et monitoring.', features: ['Audit de sécurité', 'Déploiement cloud', 'SSL, HTTPS, protection DDoS', 'Sauvegardes automatiques', 'Monitoring & alertes'] },
      ],
    },
    projects: {
      label: 'Réalisations',
      title: 'Nos',
      titleSpan: 'Projets',
      sub: 'Des solutions réelles, déployées en production, utilisées par de vrais clients.',
      badge: 'En production · kabrakopticpro.com',
      visitBtn: 'Visiter kabrakopticpro.com',
      similarBtn: 'Projet similaire ?',
      desc: 'Une plateforme SaaS complète pour les opticiens — gestion des ventes, inventaire, patients, assurances et prescriptions en un seul endroit. Multi-tenant, multi-magasins, PDF automatisés, analytics temps réel.',
      features: ['Gestion multi-magasins', 'Prescriptions & ordonnances PDF', 'Suivi patients & historique', 'Gestion des stocks', 'Assurances & mutuelles', 'Analytics temps réel'],
      ctaTitle: 'Vous avez un projet similaire ?',
      ctaSub: 'Discutons de votre idée. On construit des solutions sur-mesure, adaptées à votre secteur et votre budget.',
      ctaBtn1: 'Discuter d\'un projet',
      ctaBtn2: 'Voir Kabrak Optic Pro',
    },
    contact: {
      label: 'Parlons-en',
      title: 'Contactez-nous',
      sub: 'Vous avez un projet, une question ou envie de collaborer ? On vous répond en moins de 24h.',
      waTitle: 'WhatsApp Direct',
      waSub: 'La façon la plus rapide pour nous joindre. Réponse en moins d\'1h pendant les heures ouvrables.',
      waBtn: 'Écrire sur WhatsApp',
      availability: 'Lun–Sam, 8h–18h WAT',
      location: 'Cameroun — Afrique centrale',
      formTitle: 'Envoyez-nous un message',
      formSub: 'Décrivez votre projet et on vous revient avec une proposition concrète.',
      labelName: 'Nom complet *',
      labelEmail: 'Email *',
      labelService: 'Service souhaité',
      labelMsg: 'Votre message *',
      placeholderName: 'Moussa Njike',
      placeholderEmail: 'vous@exemple.com',
      placeholderMsg: 'Décrivez votre projet, vos besoins, votre budget estimé...',
      serviceOptions: ['Développement Web', 'Application Mobile', 'Intelligence Artificielle', 'Solutions Digitales', 'Data & Analytics', 'Sécurité & Infrastructure', 'Autre'],
      sendBtn: 'Envoyer le message',
      sending: 'Envoi en cours...',
      sentTitle: 'Message envoyé !',
      sentSub: 'Merci pour votre message. On vous répond dans les 24h. En attendant, vous pouvez aussi nous joindre sur WhatsApp.',
      continueWa: 'Continuer sur WhatsApp',
      nextTitle: 'Ce qui se passe ensuite',
      nextSteps: ['On vous répond sous 24h', 'Appel découverte de 30 min', 'Devis détaillé sous 48h', 'Démarrage du projet'],
    },
  },
  en: {
    nav: {
      home: 'Home', about: 'About', services: 'Services',
      projects: 'Projects', contact: 'Contact', cta: 'Contact us',
    },
    footer: {
      tagline: 'Digital solutions that work for Africa. Designed and built in Cameroon.',
      nav: 'Navigation', contact: 'Contact', startProject: 'Start a project',
      builtIn: 'Built in', rights: 'All rights reserved.',
    },
    whatsapp: 'Hello KABRAK Eng, I would like to discuss a project.',
    home: {
      heroTitle1: 'Empowering African',
      heroTitle2: 'Businesses',
      heroTitle3: 'Through',
      heroTitle4: 'Smart Technology',
      heroSub: 'KABRAK Eng builds custom digital solutions tailored to African realities — fast, robust and built to scale.',
      heroBtn1: 'Explore our services',
      heroBtn2: 'Contact us',
      trustPills: ['100% Made in Africa', 'Mobile-first', 'Low-bandwidth ready', 'Fast delivery'],
      servicesLabel: 'What we do',
      servicesTitle: 'Our areas of expertise',
      servicesSub: 'Concrete solutions that simplify, automate and transform your business.',
      servicesLink: 'View all services',
      services: [
        { title: 'Software Development', sub: 'Platforms, SaaS & web apps', desc: 'Custom web applications and full SaaS platforms. From prototype to scalable product, we handle the full cycle.' },
        { title: 'Artificial Intelligence', sub: 'Automation & predictions', desc: 'Automate your processes, make better decisions. Chatbots, sales predictions, smart recommendations.' },
        { title: 'Digital Solutions', sub: 'Tools built for Africa', desc: 'Tools adapted to local constraints: slow connections, Mobile Money, simple and powerful interfaces.' },
      ],
      impactLabel: 'Our impact',
      impactTitle1: 'We build technology',
      impactTitle2: 'that works for Africa',
      impactSub: 'We create solutions adapted to African realities — accessible, durable and ready to scale.',
      stats: [
        { num: '+10', label: 'Projects delivered' },
        { num: '+5', label: 'Satisfied clients' },
        { num: '1', label: 'Live SaaS product' },
        { num: '100%', label: 'Africa focus' },
      ],
      pillars: [
        { title: 'SME Digitalization', desc: 'Helping small and medium businesses transition to digital effectively.' },
        { title: 'Increased productivity', desc: 'Our tools reduce manual work and increase our clients\' revenue.' },
        { title: 'Accessible tech', desc: 'Interfaces optimized for 3G, integrated Mobile Money, offline mode.' },
      ],
      featuredLabel: 'Featured project',
      featuredTitle: 'What we have built',
      featuredBadge: 'Already live in production',
      featuredDesc: 'A complete SaaS platform for opticians — sales management, inventory, patients, insurance and prescriptions in one place. Multi-tenant, multi-store, automated PDFs, real-time analytics.',
      featuredVisit: 'Visit kabrakopticpro.com',
      featuredMore: 'Learn more',
      featuredAllProjects: 'View all projects',
      testimonialsLabel: 'Testimonials',
      testimonialsTitle: 'What our clients say',
      testimonials: [
        { name: 'Nabil A.', role: 'Manager, Saoudia Optique — Douala', quote: 'KABRAK Eng delivered in 2 weeks what I had been waiting for for months. Clean interface, top performance — exactly what I needed.' },
        { name: 'Thierry Bogo', role: 'Director, Bogo System — Exchange office', quote: 'The management software they developed for our exchange office transformed our operations. Fast, reliable and perfectly tailored to our needs.' },
        { name: 'Aminatou K.', role: 'Manager, Optique Cabinet — Yaoundé', quote: 'Very professional and responsive team. The platform simplifies our daily management and our clients are impressed by the smoothness of the service.' },
      ],
      ctaTitle: 'Ready to transform your business?',
      ctaSub: 'Let\'s discuss your project. In 30 minutes, we\'ll propose a concrete solution adapted to your budget.',
      ctaBtn1: 'Start a project',
      ctaBtn2: 'View our projects',
    },
    about: {
      label: 'Our story',
      title: 'About',
      sub: 'A technology company born in Africa, built for Africa — with a global ambition.',
      whoLabel: 'Who we are',
      whoTitle1: 'Technology at the service of',
      whoTitle2: 'African entrepreneurs',
      whoP1: 'KABRAK Eng is a company specializing in creating technological solutions adapted to African challenges. We design software platforms, web applications and digital tools that truly work in local conditions — limited connection, Mobile Money, French interfaces.',
      whoP2: 'Our ambition: to become the reference tech partner for SMEs and startups in Central and sub-Saharan Africa, building solutions that can scale and compete internationally.',
      tags: ['Cameroon 🇨🇲', 'African tech', 'Startup mindset', 'International'],
      guideTitle: 'What drives us',
      mission: { title: 'Our Mission', desc: 'Create accessible digital tools that help African businesses be more efficient, more competitive and more profitable.' },
      vision: { title: 'Our Vision', desc: 'Be recognized as the reference African tech studio, capable of building world-class products from the continent.' },
      values: { title: 'Our Values', desc: 'Uncompromising excellence, client proximity, adapted innovation. We deliver what we promise, on time.' },
      whyLabel: 'Why choose us',
      whyTitle: 'What sets us apart',
      why: [
        { title: 'Fast delivery', desc: 'MVP in 2 weeks. No empty promises — we code.' },
        { title: 'African context', desc: '3G, Mobile Money, local languages. We understand your market.' },
        { title: 'Quality code', desc: 'Clean, scalable and maintainable architecture long-term.' },
        { title: 'Client proximity', desc: 'A dedicated contact. You talk directly to the developers.' },
      ],
      ctaTitle: 'Let\'s work together',
      ctaSub: 'Do you have a project, an idea or a problem to solve? We\'re here for that.',
      ctaBtn: 'Start the conversation',
    },
    services: {
      label: 'What we do',
      title: 'Our',
      titleSpan: 'Services',
      sub: 'From a simple website to a complex SaaS platform — we cover the full spectrum of digital development, adapted to African needs and realities.',
      quoteBtn: 'Request a quote',
      processLabel: 'How it works',
      processTitle: 'Our process',
      process: [
        { num: '01', title: 'Discovery', desc: '30-min call to understand your needs, budget and timeline.' },
        { num: '02', title: 'Proposal', desc: 'Detailed quote, planning and technical architecture within 48h.' },
        { num: '03', title: 'Development', desc: 'Short sprints with regular demos. You track the progress.' },
        { num: '04', title: 'Delivery', desc: 'Deployment, training and support included in every project.' },
      ],
      ctaBadge: 'Response within 24h guaranteed',
      ctaTitle: 'Have a project in mind?',
      ctaSub: 'Describe your idea. We\'ll propose a concrete solution, a timeline and a realistic budget.',
      ctaBtn: 'Get a free quote',
      list: [
        { title: 'Web Development', subtitle: 'Custom sites & platforms', desc: 'Modern web applications, SaaS platforms, dashboards, client portals. Clean code and fast delivery.', features: ['Professional showcase site', 'Web app / SaaS', 'Dashboard & back-office', 'REST API & integrations', 'Deployment & maintenance'] },
        { title: 'Artificial Intelligence', subtitle: 'Automation & predictions', desc: 'Integrate AI into your business processes. Smart chatbots, data analysis, sales predictions.', features: ['Chatbot & AI assistant', 'Predictions & recommendations', 'Data analysis', 'Task automation', 'Natural language processing'], badge: 'Popular' },
        { title: 'Mobile Applications', subtitle: 'Android & iOS', desc: 'High-performance cross-platform mobile apps. Intuitive interface, offline mode, integrated Mobile Money.', features: ['Android & iOS app', 'Mobile-first intuitive interface', 'Offline mode', 'Mobile Money integration', 'Push notifications'] },
        { title: 'Digital Solutions', subtitle: 'Digital transformation', desc: 'Digitize your internal processes, automate your workflows and gain operational efficiency.', features: ['Digital audit & consulting', 'Process digitalization', 'Management systems (ERP/CRM)', 'Training & support', 'Support & maintenance'] },
        { title: 'Data & Analytics', subtitle: 'Your data, your decisions', desc: 'Transform your raw data into actionable insights. Real-time dashboards, automated reports.', features: ['Real-time dashboards', 'Automated reports', 'KPIs & business metrics', 'Trend analysis', 'Exports & integrations'] },
        { title: 'Security & Infrastructure', subtitle: 'Reliable, secure, scalable', desc: 'Security audit, server setup, cloud deployment, automatic backups and monitoring.', features: ['Security audit', 'Cloud deployment', 'SSL, HTTPS, DDoS protection', 'Automatic backups', 'Monitoring & alerts'] },
      ],
    },
    projects: {
      label: 'Portfolio',
      title: 'Our',
      titleSpan: 'Projects',
      sub: 'Real solutions, deployed in production, used by real clients.',
      badge: 'Live · kabrakopticpro.com',
      visitBtn: 'Visit kabrakopticpro.com',
      similarBtn: 'Similar project?',
      desc: 'A complete SaaS platform for opticians — sales management, inventory, patients, insurance and prescriptions in one place. Multi-tenant, multi-store, automated PDFs, real-time analytics.',
      features: ['Multi-store management', 'PDF prescriptions & orders', 'Patient tracking & history', 'Inventory management', 'Insurance & mutual funds', 'Real-time analytics'],
      ctaTitle: 'Have a similar project?',
      ctaSub: 'Let\'s discuss your idea. We build custom solutions, adapted to your sector and budget.',
      ctaBtn1: 'Discuss a project',
      ctaBtn2: 'See Kabrak Optic Pro',
    },
    contact: {
      label: 'Let\'s talk',
      title: 'Contact us',
      sub: 'Have a project, a question or want to collaborate? We reply within 24h.',
      waTitle: 'WhatsApp Direct',
      waSub: 'The fastest way to reach us. Response within 1h during business hours.',
      waBtn: 'Write on WhatsApp',
      availability: 'Mon–Sat, 8am–6pm WAT',
      location: 'Cameroon — Central Africa',
      formTitle: 'Send us a message',
      formSub: 'Describe your project and we\'ll come back with a concrete proposal.',
      labelName: 'Full name *',
      labelEmail: 'Email *',
      labelService: 'Service needed',
      labelMsg: 'Your message *',
      placeholderName: 'Moussa Njike',
      placeholderEmail: 'you@example.com',
      placeholderMsg: 'Describe your project, your needs, your estimated budget...',
      serviceOptions: ['Web Development', 'Mobile Application', 'Artificial Intelligence', 'Digital Solutions', 'Data & Analytics', 'Security & Infrastructure', 'Other'],
      sendBtn: 'Send message',
      sending: 'Sending...',
      sentTitle: 'Message sent!',
      sentSub: 'Thank you for your message. We\'ll reply within 24h. In the meantime, you can also reach us on WhatsApp.',
      continueWa: 'Continue on WhatsApp',
      nextTitle: 'What happens next',
      nextSteps: ['We reply within 24h', '30-min discovery call', 'Detailed quote within 48h', 'Project kickoff'],
    },
  },
};

export function LangProvider({ children }) {
  const [lang, setLang] = useState('fr');
  const t = translations[lang];
  return (
    <LangContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LangContext.Provider>
  );
}

export function useLang() {
  return useContext(LangContext);
}
